# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IeUVSUqA4QHDC5eWo26xrtY2s_vRMiMZ
"""

# memoization_module.py

# empty dictionary to store results
memo = {}

#Function to check if a route result already exists
def get_cached_result(source, destination):
    """
    Check if the shortest path result between
    the given source and destination is already cached.
    """
    key = (source, destination)
    if key in memo:
        print("\n✅ Using cached result (no recalculation needed).")
        distance, path = memo[key]
        print(f"Shortest distance from {source} to {destination}: {distance} km")
        print(f"Path taken: {path}")
        return distance, path
    else:
        return None

#  Function to store a new result in the cache
def store_result(source, destination, distance, path):
    """
    Store a newly computed shortest path means
    jo n
    """
    key = (source, destination)
    memo[key] = (distance, path)
    print(f"\n🧠 Result stored in cache for {source} → {destination}")

# Function to view all cached routes
def show_all_cached_routes():
    """Display all stored route results."""
    if not memo:
        print("\n⚠️ No routes cached yet.")
        return
    print("\n📜 Cached Routes:")
    for (source, destination), (distance, path) in memo.items():
        print(f"{source} → {destination}: {distance} km | Path: {path}")

