# -*- coding: utf-8 -*-
"""optimal_route_planner_main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SifQeat5i6oHhkAVASnY8G0QyVPTR5w_
"""

# optimal_route_planner_main.py
# -------------------------------------------------
# Main file that connects:
# 1. Bellman-Ford Algorithm (Agastya)
# 2. Memoization (Harsh)
# 3. Visualization Interface (Nayan)
# -------------------------------------------------

from memoization_module import get_cached_result, store_result
from visualization_interface import visualize_path
from bellman_ford_module import bellman_ford_shortest_path   # <-- see note below

# Step 1: Available cities
cities = ['CityA','CityB','CityC','CityD','CityE','CityF','CityG','CityH','CityI','CityJ']

print("Available cities:", cities)
source = input("Enter the source city: ")
destination = input("Enter the destination city: ")

if source not in cities or destination not in cities:
    print("Invalid city name entered. Please run again with correct names.")
    exit()

# Check if this route is already cached
cached = get_cached_result(source, destination)
if cached:
    # If result found, visualize directly
    distance, path = cached
    visualize_path(source, destination, path, distance)
    exit()

# If not cached, compute using Bellman-Ford
distance, path = bellman_ford_shortest_path(source, destination)

# Store result in memoization cache
store_result(source, destination, distance, path)

# Visualize the computed shortest path
visualize_path(source, destination, path, distance)

