# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QY1TABazzoUCWn-ISOfPF5F5xSSCCD64
"""

# visualization_interface.py
import networkx as nx
import matplotlib.pyplot as plt
#NetworkX — used to create and handle graph structures (nodes and edges).
#Matplotlib — used to draw and display the graph visually.

def visualize_path(source, destination, path, distance):
    """Display the cities graph and highlight the shortest path."""

    roads = [
        ('CityA', 'CityB', 50),
        ('CityA', 'CityC', 30),
        ('CityB', 'CityC', 20),
        ('CityB', 'CityD', 40),
        ('CityC', 'CityD', 10),
        ('CityC', 'CityE', 60),
        ('CityD', 'CityE', 30),
        ('CityD', 'CityF', 20),
        ('CityE', 'CityG', 50),
        ('CityF', 'CityG', 30),
        ('CityF', 'CityH', 40),
        ('CityG', 'CityI', 60),
        ('CityH', 'CityI', 30),
        ('CityI', 'CityJ', 50),
        ('CityH', 'CityJ', 70)
    ]

    G = nx.DiGraph()
    for u, v, w in roads:
        G.add_edge(u, v, weight=w)
        #Creates a directed graph (DiGraph).Each edge stores its weight (distance).Adds all cities and their road connections into the graph.

    pos = nx.spring_layout(G, seed=42)

    nx.draw_networkx_edges(G, pos, edge_color='lightgray', width=1)
    nx.draw_networkx_nodes(G, pos, node_color='skyblue', node_size=1200)
    nx.draw_networkx_labels(G, pos, font_size=10, font_weight='bold')

    edge_path = list(zip(path, path[1:]))
    nx.draw_networkx_edges(G, pos, edgelist=edge_path, edge_color='red', width=3)
    nx.draw_networkx_nodes(G, pos, nodelist=path, node_color='orange', node_size=1300)
    #Sabse se chota path find karta hai with red line and orange colour mee cities hoti hai jo path mee aati hai

    edge_labels = nx.get_edge_attributes(G, 'weight')
    nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels, font_size=8)
   
    plt.title(f"Optimal Route from {source} to {destination}\n(Distance: {distance} km)")
    plt.axis('off')
    plt.show()
 #Displays distance labels (weights) next to each road.Adds a title showing the route and total distance.

